### PR TITLE
fixed the issue

### PR DESCRIPTION
**Pull request by attreyee-muk**
# Description

- Fixes issue number <#Issue number>

<hr>

# Checklist:

- [x] I follow Contributing Guidelines & Code of conduct of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by preyashyadav** [comment]
Hey, the change looks good for a desktop site but it's not responsive. Can you work on making it responsive.

image

**Comment by attreyee-muk** [comment]
Okay, I will do it. Is your repo participating in hacktoberfest?

**Comment by preyashyadav** [comment]
Yes, it's participating.
I'm adding the "hacktoberfest accepted" label to it so that it can count for your contribution and show up on your profile on Hacktoberfest website, but we can only merge it after you fix the responsiveness issue.

**Comment by attreyee-muk** [comment]
Okay, np.  I will solve the issue.

**Comment by preyashyadav** [comment]
Ok cool😊

**Comment by attreyee-muk** [comment]
I made the required changes. Pls see and do let me know if there is still any problem. Thank you!

**Comment by preyashyadav** [comment]
Good job @a-muk 👏👏. Thanks for contributing 😊

**Comment by attreyee-muk** [comment]
Thanks a lot!!

**Pull request merged**
